### PR TITLE
Replaces `Ember.K` usage with JavaScript syntax

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by locks** [comment]
There is an [`Ember.K` deprecation RFC](https://github.com/emberjs/rfcs/pull/178) currently being proposed to the community by @cibernox. We did a [quick check](https://github.com/cibernox/rfcs/blob/db4cd4bd8b774990f1b5187cf8e116075320de4d/text/0000-deprecate-ember-k.md#addenda) across published addons for usage and I thought I'd send a couple PRs because I believe that using JavaScript syntax instead of `Ember.K` removes one surprise/API you have to learn to understand the code.

**Comment by locks** [comment]
Not sure what's up with the failing build, anything I can do?

**Comment by kagemusha** [comment]
sounds good.  thx.  seems rerunning the build fixed things :-)

**Comment by locks** [comment]
Thanks 😀

**Pull request merged**
